/**
 * Maps country names to a representative IANA time zone, so the converter can
 * be searched by country (IANA ids are city-based, e.g. Tajikistan is
 * "Asia/Dushanbe"). For multi-zone countries this is the capital/primary zone.
 * Add more freely — it only feeds search, never validation.
 */
export const COUNTRY_TIMEZONES: Array<[string, string]> = [
  ['Afghanistan', 'Asia/Kabul'],
  ['Albania', 'Europe/Tirane'],
  ['Algeria', 'Africa/Algiers'],
  ['Andorra', 'Europe/Andorra'],
  ['Angola', 'Africa/Luanda'],
  ['Argentina', 'America/Argentina/Buenos_Aires'],
  ['Armenia', 'Asia/Yerevan'],
  ['Australia', 'Australia/Sydney'],
  ['Austria', 'Europe/Vienna'],
  ['Azerbaijan', 'Asia/Baku'],
  ['Bahamas', 'America/Nassau'],
  ['Bahrain', 'Asia/Bahrain'],
  ['Bangladesh', 'Asia/Dhaka'],
  ['Barbados', 'America/Barbados'],
  ['Belarus', 'Europe/Minsk'],
  ['Belgium', 'Europe/Brussels'],
  ['Belize', 'America/Belize'],
  ['Benin', 'Africa/Porto-Novo'],
  ['Bhutan', 'Asia/Thimphu'],
  ['Bolivia', 'America/La_Paz'],
  ['Bosnia and Herzegovina', 'Europe/Sarajevo'],
  ['Botswana', 'Africa/Gaborone'],
  ['Brazil', 'America/Sao_Paulo'],
  ['Brunei', 'Asia/Brunei'],
  ['Bulgaria', 'Europe/Sofia'],
  ['Burkina Faso', 'Africa/Ouagadougou'],
  ['Burundi', 'Africa/Bujumbura'],
  ['Cambodia', 'Asia/Phnom_Penh'],
  ['Cameroon', 'Africa/Douala'],
  ['Canada', 'America/Toronto'],
  ['Cape Verde', 'Atlantic/Cape_Verde'],
  ['Central African Republic', 'Africa/Bangui'],
  ['Chad', 'Africa/Ndjamena'],
  ['Chile', 'America/Santiago'],
  ['China', 'Asia/Shanghai'],
  ['Colombia', 'America/Bogota'],
  ['Comoros', 'Indian/Comoro'],
  ['Congo', 'Africa/Brazzaville'],
  ['Costa Rica', 'America/Costa_Rica'],
  ['Croatia', 'Europe/Zagreb'],
  ['Cuba', 'America/Havana'],
  ['Cyprus', 'Asia/Nicosia'],
  ['Czechia', 'Europe/Prague'],
  ['Czech Republic', 'Europe/Prague'],
  ['Democratic Republic of the Congo', 'Africa/Kinshasa'],
  ['Denmark', 'Europe/Copenhagen'],
  ['Djibouti', 'Africa/Djibouti'],
  ['Dominican Republic', 'America/Santo_Domingo'],
  ['Ecuador', 'America/Guayaquil'],
  ['Egypt', 'Africa/Cairo'],
  ['El Salvador', 'America/El_Salvador'],
  ['Equatorial Guinea', 'Africa/Malabo'],
  ['Eritrea', 'Africa/Asmara'],
  ['Estonia', 'Europe/Tallinn'],
  ['Eswatini', 'Africa/Mbabane'],
  ['Ethiopia', 'Africa/Addis_Ababa'],
  ['Fiji', 'Pacific/Fiji'],
  ['Finland', 'Europe/Helsinki'],
  ['France', 'Europe/Paris'],
  ['Gabon', 'Africa/Libreville'],
  ['Gambia', 'Africa/Banjul'],
  ['Georgia', 'Asia/Tbilisi'],
  ['Germany', 'Europe/Berlin'],
  ['Ghana', 'Africa/Accra'],
  ['Greece', 'Europe/Athens'],
  ['Guatemala', 'America/Guatemala'],
  ['Guinea', 'Africa/Conakry'],
  ['Guyana', 'America/Guyana'],
  ['Haiti', 'America/Port-au-Prince'],
  ['Honduras', 'America/Tegucigalpa'],
  ['Hong Kong', 'Asia/Hong_Kong'],
  ['Hungary', 'Europe/Budapest'],
  ['Iceland', 'Atlantic/Reykjavik'],
  ['India', 'Asia/Kolkata'],
  ['Indonesia', 'Asia/Jakarta'],
  ['Iran', 'Asia/Tehran'],
  ['Iraq', 'Asia/Baghdad'],
  ['Ireland', 'Europe/Dublin'],
  ['Israel', 'Asia/Jerusalem'],
  ['Italy', 'Europe/Rome'],
  ['Ivory Coast', 'Africa/Abidjan'],
  ['Jamaica', 'America/Jamaica'],
  ['Japan', 'Asia/Tokyo'],
  ['Jordan', 'Asia/Amman'],
  ['Kazakhstan', 'Asia/Almaty'],
  ['Kenya', 'Africa/Nairobi'],
  ['Kosovo', 'Europe/Belgrade'],
  ['Kuwait', 'Asia/Kuwait'],
  ['Kyrgyzstan', 'Asia/Bishkek'],
  ['Laos', 'Asia/Vientiane'],
  ['Latvia', 'Europe/Riga'],
  ['Lebanon', 'Asia/Beirut'],
  ['Lesotho', 'Africa/Maseru'],
  ['Liberia', 'Africa/Monrovia'],
  ['Libya', 'Africa/Tripoli'],
  ['Liechtenstein', 'Europe/Vaduz'],
  ['Lithuania', 'Europe/Vilnius'],
  ['Luxembourg', 'Europe/Luxembourg'],
  ['Macau', 'Asia/Macau'],
  ['Madagascar', 'Indian/Antananarivo'],
  ['Malawi', 'Africa/Blantyre'],
  ['Malaysia', 'Asia/Kuala_Lumpur'],
  ['Maldives', 'Indian/Maldives'],
  ['Mali', 'Africa/Bamako'],
  ['Malta', 'Europe/Malta'],
  ['Mauritania', 'Africa/Nouakchott'],
  ['Mauritius', 'Indian/Mauritius'],
  ['Mexico', 'America/Mexico_City'],
  ['Moldova', 'Europe/Chisinau'],
  ['Monaco', 'Europe/Monaco'],
  ['Mongolia', 'Asia/Ulaanbaatar'],
  ['Montenegro', 'Europe/Podgorica'],
  ['Morocco', 'Africa/Casablanca'],
  ['Mozambique', 'Africa/Maputo'],
  ['Myanmar', 'Asia/Yangon'],
  ['Namibia', 'Africa/Windhoek'],
  ['Nepal', 'Asia/Kathmandu'],
  ['Netherlands', 'Europe/Amsterdam'],
  ['New Zealand', 'Pacific/Auckland'],
  ['Nicaragua', 'America/Managua'],
  ['Niger', 'Africa/Niamey'],
  ['Nigeria', 'Africa/Lagos'],
  ['North Korea', 'Asia/Pyongyang'],
  ['North Macedonia', 'Europe/Skopje'],
  ['Norway', 'Europe/Oslo'],
  ['Oman', 'Asia/Muscat'],
  ['Pakistan', 'Asia/Karachi'],
  ['Palestine', 'Asia/Gaza'],
  ['Panama', 'America/Panama'],
  ['Papua New Guinea', 'Pacific/Port_Moresby'],
  ['Paraguay', 'America/Asuncion'],
  ['Peru', 'America/Lima'],
  ['Philippines', 'Asia/Manila'],
  ['Poland', 'Europe/Warsaw'],
  ['Portugal', 'Europe/Lisbon'],
  ['Qatar', 'Asia/Qatar'],
  ['Romania', 'Europe/Bucharest'],
  ['Russia', 'Europe/Moscow'],
  ['Rwanda', 'Africa/Kigali'],
  ['Saudi Arabia', 'Asia/Riyadh'],
  ['Senegal', 'Africa/Dakar'],
  ['Serbia', 'Europe/Belgrade'],
  ['Seychelles', 'Indian/Mahe'],
  ['Sierra Leone', 'Africa/Freetown'],
  ['Singapore', 'Asia/Singapore'],
  ['Slovakia', 'Europe/Bratislava'],
  ['Slovenia', 'Europe/Ljubljana'],
  ['Somalia', 'Africa/Mogadishu'],
  ['South Africa', 'Africa/Johannesburg'],
  ['South Korea', 'Asia/Seoul'],
  ['South Sudan', 'Africa/Juba'],
  ['Spain', 'Europe/Madrid'],
  ['Sri Lanka', 'Asia/Colombo'],
  ['Sudan', 'Africa/Khartoum'],
  ['Suriname', 'America/Paramaribo'],
  ['Sweden', 'Europe/Stockholm'],
  ['Switzerland', 'Europe/Zurich'],
  ['Syria', 'Asia/Damascus'],
  ['Taiwan', 'Asia/Taipei'],
  ['Tajikistan', 'Asia/Dushanbe'],
  ['Tanzania', 'Africa/Dar_es_Salaam'],
  ['Thailand', 'Asia/Bangkok'],
  ['Togo', 'Africa/Lome'],
  ['Trinidad and Tobago', 'America/Port_of_Spain'],
  ['Tunisia', 'Africa/Tunis'],
  ['Turkey', 'Europe/Istanbul'],
  ['Turkmenistan', 'Asia/Ashgabat'],
  ['Uganda', 'Africa/Kampala'],
  ['Ukraine', 'Europe/Kyiv'],
  ['United Arab Emirates', 'Asia/Dubai'],
  ['United Kingdom', 'Europe/London'],
  ['United States', 'America/New_York'],
  ['Uruguay', 'America/Montevideo'],
  ['Uzbekistan', 'Asia/Tashkent'],
  ['Venezuela', 'America/Caracas'],
  ['Vietnam', 'Asia/Ho_Chi_Minh'],
  ['Yemen', 'Asia/Aden'],
  ['Zambia', 'Africa/Lusaka'],
  ['Zimbabwe', 'Africa/Harare'],
];

export interface ZoneOption {
  zone: string;
  label: string;
  search: string;
}

/**
 * Builds the searchable option list: every IANA zone plus a friendly label
 * (city + region) and the names of any countries that map to it, so users can
 * search by country, city or zone id.
 */
export function buildZoneOptions(zones: string[]): ZoneOption[] {
  const countriesByZone = new Map<string, string[]>();
  for (const [country, zone] of COUNTRY_TIMEZONES) {
    const list = countriesByZone.get(zone) ?? [];
    list.push(country);
    countriesByZone.set(zone, list);
  }

  return zones.map((zone) => {
    const parts = zone.split('/');
    const city = (parts[parts.length - 1] ?? zone).replace(/_/g, ' ');
    const region = parts.length > 1 ? parts[0] : '';
    const countries = countriesByZone.get(zone) ?? [];
    const label = countries.length
      ? `${city} — ${countries.join(', ')}`
      : region
        ? `${city} — ${region}`
        : city;
    const search = [zone, city, region, ...countries].join(' ').toLowerCase();
    return { zone, label, search };
  });
}
